
export type UploadStatus = "pending" | "processing" | "completed" | "error";

export interface Upload {
  id: string;
  userId: string;
  title: string;
  filename: string;          // Original file name
  storagePath: string;       // Path in Firebase Storage
  fileType: string;          // "pdf" or "pptx"
  slideUrl: string;          // URL to access the file
  script?: string;           // Generated by AI (empty until AI integration)
  videoUrl?: string;         // Generated video URL (empty until AI integration)
  thumbnailUrl?: string;     // Thumbnail for the video
  status: UploadStatus;
  errorMessage?: string;
  createdAt: string;
  updatedAt: string;
}
